# Generated by Django 3.1.2 on 2021-09-17 20:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('refuel', '0003_auto_20210917_2028'),
        ('vehicle', '0002_auto_20210915_0337'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Vehicle_Driver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='anssurancetype',
            name='company_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='vehicle.anssurancecompany', verbose_name='company'),
        ),
        migrations.AlterField(
            model_name='certificateoffitness',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='vehicle.vehicle'),
        ),
        migrations.AlterField(
            model_name='certificatofcerculation',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='vehicle.vehicle'),
        ),
        migrations.AlterField(
            model_name='city',
            name='region_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='vehicle.region'),
        ),
        migrations.AlterField(
            model_name='modelspecificationvalue',
            name='specification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vehicle.vehiclespecification'),
        ),
        migrations.AlterField(
            model_name='modelspecificationvalue',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vehicle.vehicle'),
        ),
        migrations.AlterField(
            model_name='specialcertificat',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vehicle.vehicle'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='gaz_station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Station', to='refuel.gazstation'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Vehicle_Model', to='vehicle.vehiclemodel'),
        ),
        migrations.AlterField(
            model_name='vehicleanssurancespecification',
            name='anssurance_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vehicle.anssurancetype', verbose_name='Anssurance Type'),
        ),
        migrations.AlterField(
            model_name='vehicleanssurancespecification',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vehicle.vehicle', verbose_name='Vehicle'),
        ),
        migrations.AlterField(
            model_name='vehiclehome',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vehicle.vehiclemodel'),
        ),
        migrations.AlterField(
            model_name='vehiclemodel',
            name='make',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='vehicle.make'),
        ),
        migrations.AlterField(
            model_name='vehiclespecification',
            name='vehicle_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vehicle.vehiclemodel'),
        ),
        migrations.DeleteModel(
            name='GazStation',
        ),
    ]
