# Generated by Django 3.1.2 on 2021-09-15 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refuel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='refuel',
            name='snitch',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Mouchard KM'),
        ),
    ]
