# Generated by Django 3.1.2 on 2021-09-17 20:28

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vehicle', '0002_auto_20210915_0337'),
        ('refuel', '0002_refuel_snitch'),
    ]

    operations = [
        migrations.AddField(
            model_name='refuel',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='responsable_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='refuel',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='vehicle.vehicle'),
        ),
        migrations.CreateModel(
            name='GazStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, unique=True)),
                ('geo_localization', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(default=True)),
                ('Controlor_id', models.ForeignKey(blank=True, limit_choices_to={'is_active': True, 'is_controlor': True}, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('city_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicle.city')),
            ],
            options={
                'ordering': ['city_id', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FuelConsumption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumption', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(default=True)),
                ('Controlor_id', models.ForeignKey(blank=True, limit_choices_to={'is_active': True, 'is_controlor': True}, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Vehicle_Driver_consuption', to=settings.AUTH_USER_MODEL)),
                ('gaz_station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Station_consuption', to='refuel.gazstation')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='vehicle.vehicle')),
            ],
            options={
                'ordering': ['vehicle', '-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='refuel',
            name='gaz_station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Refuel_Station', to='refuel.gazstation'),
        ),
    ]
