# Generated by Django 3.1.2 on 2021-09-18 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('refuel', '0003_auto_20210917_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gazstation',
            name='city_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.city'),
        ),
    ]
